### ISSUE TITLE
running app

### ISSUE THREAD

**Issue by kpwiley28** [conarwelsh/kevin-learning#1]
**Looks like it's getting hung up on import.  I initially ran 'npm install' and it ran everything.  I thought this may have been a dependencies issue so I tried to run it again and nothing installed.  Also 'node_modules' shows react  and react-dom in it so I'm not sure why it can't import.  I'm sure it's a stupid little thing I'm missing as I haven't run an app this way before but I'm getting hung up.  Terminal error code is below.

Stephanie-Boccellas-MacBook-Pro:kevin-learning-master Stevie$ node app
/Users/Stevie/Desktop/kevin-learning-master/app/index.js:4
import React from 'react'
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by kpwiley28** [comment]
So now I've tried running 'babel-node index.js' in the app folder and got a reference error

), document.getElementByID('root'));
   ^

ReferenceError: document is not defined
    at Object.<anonymous> (index.js:19:2)
    at Module._compile (module.js:409:26)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at /usr/local/lib/node_modules/babel-cli/lib/_babel-node.js:160:24
    at Object.<anonymous> (/usr/local/lib/node_modules/babel-cli/lib/_babel-node.js:161:7)
    at Module._compile (module.js:409:26)


I also tried running 'babel-node ./server' from the root directory because that's what is in package.json but I got an error with the web socket.  I'm not sure if I'm missing something with the sockets but I didn't think I was even touching those just yet.

201
    throw new Error(msg);
    ^

Error: You are trying to attach socket.io to an express request handler function. Please pass a http.Server instance.
    at Server.listen.Server.attach (/Users/Stevie/Desktop/kevin-learning-master/node_modules/socket.io/lib/index.js:201:11)
    at new Server (/Users/Stevie/Desktop/kevin-learning-master/node_modules/socket.io/lib/index.js:50:17)
    at Server (/Users/Stevie/Desktop/kevin-learning-master/node_modules/socket.io/lib/index.js:38:41)
    at Object.<anonymous> (index.js:13:12)
    at Module._compile (module.js:409:26)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by conarwelsh** [comment]
I added what was missing to get it running properly.  There are 3 different scripts you should be running in terminal:

```bash
\\builds your CSS files
npm run styles

\\builds your client-side JS files
npm run webpack

\\builds and runs your web server
npm start
```

look through `package.json` to see what they are doing
